### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by AtomicKRG** [Heady20006/devProp#2]
Hi when I add a with L a appartment on my server the appartment is not working. I restart the server but it does not work. I see the purple circle but nothing comes like -Press E to interact- 
Please help me

**Comment by Heady20006** [comment]
You know that this tool is for devs?!
So if you are a dev you should fix it by your own. 

But okay... 
Any errors in console?
Each property didnt work or just a special one?

**Comment by AtomicKRG** [comment]
I have fixed it.

Fred Richter <notifications@github.com> schrieb am Di., 23. Apr. 2019,
06:50:
